version: '3.8'

services:
  # Servicio de MongoDB
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - readybear-network
    volumes:
      - mongo-data:/data/db

  # Servicio de autenticación
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo-db
    env_file:
      - ./auth-service/.env
    networks:
      - readybear-network

  # Servicio para eliminar productos
  deleteproduct:
    build: ./deleteproduct
    container_name: deleteproduct
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongo-db
    env_file:
      - ./deleteproduct/.env
    networks:
      - readybear-network

  # Servicio principal de productos
  productservice:
    build: ./productservice
    container_name: productservice
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - mongo-db
    env_file:
      - ./productservice/.env
    networks:
      - readybear-network

  # Servicio para leer productos
  readproduct:
    build: ./readproduct
    container_name: readproduct
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - mongo-db
    env_file:
      - ./readproduct/.env
    networks:
      - readybear-network

  # Servicio para actualizar productos
  updateproduct:
    build: ./updateproduct
    container_name: updateproduct
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - mongo-db
    env_file:
      - ./updateproduct/.env
    networks:
      - readybear-network

  # Frontend en React con Vite
  frontendproduct:
    build: ./frontendproduct
    container_name: frontendproduct
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - productservice
    env_file:
      - ./frontendproduct/.env
    networks:
      - readybear-network

networks:
  readybear-network:
    driver: bridge

volumes:
  mongo-data:
