# Usar Node.js como base
FROM node:18-alpine

# Definir directorio de trabajo
WORKDIR /app

# Copiar dependencias y archivos
COPY package*.json ./
RUN npm install
COPY . .

# Exponer puerto y ejecutar servidor
EXPOSE 5002
CMD ["node", "server.js"]
