#name: Deploy Microservices

#on:
  #push:
    #branches:
      #- qa

#jobs:
  #deploy:
    #runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #service: [pruebafront, back, document, ReadyBear-Instance, pruebafront2]
        #secret_ip: [IP_2, IP_3, IP_4, IP_5, IP_6]
    #steps:
      #- name: Checkout código
        #uses: actions/checkout@v4

      #- name: Configurar clave SSH
        #run: |
          #mkdir -p ~/.ssh
          #echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/readybear-key.pem
          #chmod 600 ~/.ssh/readybear-key.pem
          #ssh-keyscan ${{ secrets[matrix.secret_ip] }} >> ~/.ssh/known_hosts

      #- name: Desplegar en EC2
        #run: |
          #ssh -i ~/.ssh/readybear-key.pem ubuntu@${{ secrets[matrix.secret_ip] }} << 'EOF'
            #cd /home/ubuntu/ReadyBear26
            #git pull origin qa
            #chmod +x setup.sh setup-env.sh
            #./setup.sh
            #./setup-env.sh
            #cd ${{ matrix.service }}
            #docker-compose down
            #docker-compose up --build -d
          #EOF
